version: '3.4'

services:
  apirickandmorty2.0:
    container_name: ApiRickandMorty2.0
    build:
      args:
        source: obj/Docker/publish/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ApiRickandMorty2.0"
    volumes:
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\inetpub\\wwwroot\\bin\\ApiRickandMorty2.0.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visual-studio.project-name: "ApiRickandMorty2.0"
