version: '3.4'

services:
  apirickandmorty2.0:
    image: apirickandmorty20:dev
    container_name: ApiRickandMorty2.0
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ApiRickandMorty2.0"
    volumes:
      - C:\Users\User\Desktop\api\ApiRickandMorty2.0\ApiRickandMorty2.0:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800

